### ISSUE TITLE
Tests fail on master branch

### ISSUE THREAD

**Issue by hlerebours** [thefactory/marathon-python#180]
see dummy PR to prove it: https://github.com/thefactory/marathon-python/pull/179

**Comment by solarkennedy** [comment]
```
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
GLOB sdist-make: /home/travis/build/thefactory/marathon-python/setup.py
itest-py27 create: /home/travis/build/thefactory/marathon-python/.tox/itest-py27
[2017-03-17 12:36:20,025] INFO  Starting Marathon 1.4.0/unknown with  (mesosphere.marathon.MarathonApp:main)
Failed to load native Mesos library from /usr/local/lib:/usr/lib:/usr/lib64
[2017-03-17 12:36:20,055] ERROR Terminating 8080 due to uncaught exception in thread main:1 (mesosphere.marathon.MarathonApp:main)
java.lang.UnsatisfiedLinkError: /usr/lib/libmesos-1.1.1.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /usr/lib/libmesos-1.1.1.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:163)
	at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:188)
	at mesosphere.mesos.LibMesos$.version$lzycompute(LibMesos.scala:24)
	at mesosphere.mesos.LibMesos$.version(LibMesos.scala:22)
	at mesosphere.mesos.LibMesos$.isCompatible(LibMesos.scala:38)
	at mesosphere.marathon.MarathonApp.start(Main.scala:67)
	at mesosphere.marathon.Main$.main(Main.scala:161)
	at mesosphere.marathon.Main.main(Main.scala)
```

Also
```
Setting up mesos (1.1.1-2.0.1) ...
mesos-slave: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by mesos-slave)
mesos-slave: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by /usr/lib/libmesos-1.1.1.so)
/var/lib/dpkg/info/mesos.postinst: line 24: [: -gt: unary operator expected
/var/lib/dpkg/info/mesos.postinst: line 24: [: -gt: unary operator expected
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place
```

Something changed with the mesos builds maybe? Or travis? Not sure yet.

**Comment by hlerebours** [comment]
Maybe adding something in the .travis.yml like

addons:
  apt:
    packages:
      - libstdc++-...
