### ISSUE TITLE
Failed to import marathon in python3

### ISSUE THREAD

**Issue by strigazi** [thefactory/marathon-python#217]
in a python3 environment I can't import marathon:
$ python
Python 3.6.2 (default, Aug 11 2017, 11:59:59) 
[GCC 7.1.1 20170622 (Red Hat 7.1.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import marathon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fedora/magnum/.tox/py36/lib/python3.6/site-packages/marathon/__init__.py", line 3, in <module>
    from .client import MarathonClient
  File "/home/fedora/magnum/.tox/py36/lib/python3.6/site-packages/marathon/client.py", line 16, in <module>
    from .models.events import EventFactory, MarathonEvent
  File "/home/fedora/magnum/.tox/py36/lib/python3.6/site-packages/marathon/models/events.py", line 150, in <module>
    class EventFactory:
  File "/home/fedora/magnum/.tox/py36/lib/python3.6/site-packages/marathon/models/events.py", line 190, in EventFactory
    class_to_event = dict((v, k) for k, v in event_to_class.iteritems())
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by strigazi** [comment]
Here is the problem:
https://github.com/thefactory/marathon-python/commit/c74a4fbfdd2b75bde394e2c5ad5daab182d8975f#diff-7341e3285185c7c5ea407e0bc3f9b7ecL190

**Comment by solarkennedy** [comment]
:( I guess that means the travis coverage isn't sufficient to test this on python3.

@fengyehong would you like to fix this for python3? If not I'll have to revert your change.

**Comment by solarkennedy** [comment]
Oh wait, I misunderstood, the fix is already in master.

Got it, I'll make a point release at your request.

**Comment by fengyehong** [comment]
It's not related to code coverage.
Travis log shows python3 tests didn't ran, maybe something wrong with the configuration
