### ISSUE TITLE
__init__() got an unexpected keyword argument 'port_mappings'

### ISSUE THREAD

**Issue by yudong2015** [thefactory/marathon-python#237]
the version of marathon is 1.10.2, and the version of marathon-python is 0.9.3, then I run marathonClient.list_apps() with marathon-python, got a problem:

`Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/jack/workspace/venv/lib/python2.7/site-packages/marathon/client.py", line 197, in list_apps
    'app.tasks': embed_tasks,
  File "/Users/jack/workspace/venv/lib/python2.7/site-packages/marathon/client.py", line 63, in _parse_response
    def __repr__(self):
  File "/Users/jack/workspace/venv/lib/python2.7/site-packages/marathon/models/base.py", line 43, in from_json
    return cls(**{to_snake_case(k): v for k, v in attributes.items()})
  File "/Users/jack/workspace/venv/lib/python2.7/site-packages/marathon/models/app.py", line 113, in __init__
    else MarathonContainer.from_json(container)
  File "/Users/jack/workspace/venv/lib/python2.7/site-packages/marathon/models/base.py", line 43, in from_json
    return cls(**{to_snake_case(k): v for k, v in attributes.items()})
TypeError: __init__() got an unexpected keyword argument 'port_mappings'
`

**Comment by solarkennedy** [comment]
This surprises me, as it should have been fixed in marathon-python 0.9.1
https://github.com/thefactory/marathon-python/blob/master/CHANGELOG.md#091-2017-09-06

with https://github.com/thefactory/marathon-python/pull/213
